[package]
name = "xmlJSON"
version = "0.1.0"
authors = ["Scott Cooper <scott.cooper2@mail.mcgill.ca>"]

description = "Conversions from XML to JSON"
readme = "README.md"
license = "MIT"
repository = "https://github.com/sacooper/xmlJSON-rs"

[dependencies]
xml-rs = "*"
rustc-serialize = "*"
